### ISSUE TITLE
Writer converter to RDF graph

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#11]
Write converter to RDF Graph 

(Do it on server side, format (probably jsonld), same URI on server side router). 
On client side there should be button (export to RDF). export only comments.

Comments:
you will only be able to describe the comments. The backend doesn't understand the structure of the document itself, and...
10:44
you only have access to the document the last time it was saved. which may be 2 minutes old
10:45
other people connecting to the editor will get the current version.

akorovin
10:46 PM so you mean that outside it is not possible to get document? it needs to be saved during 2 minutes time threshold?
10:46
for example: nobody accesses the document and some user outside wants info about annotations
10:46
it is not possible
johanneswilm
10:46 PM it is possible to see what is in the comments, yes.
10:47
but it's not possible to see what is in the document, or where the comments connect in the document
10:47
and the comments may be up to two minutes delayed, if someone is in the document.
10:47
if noone is in the document, the comments will be current.

if the last user leaves, it is saved immediately
10:50
also if the user changes the title
10:51
other than that every 2 minutes, if there have been changes to the text content
10:51
if the user just has changed comments or answered comments for half an hour, the document may be half an hour old

**Comment by aw3s0me** [comment]
Library for creation of RDF: https://github.com/RDFLib/rdflib

**Comment by aw3s0me** [comment]
Fetching of rdf about annotations should be implemented by using Content-negotiation. (when we specify 'Content-type: rdf' in http header and put url: localhost/document/id -> it returns rdf data about comments)
Specific comment url in rdf graph: localhost/document/id/comments/id
Decided to use json-ld for serialization. Supported by python: rdflib.
Rdf graph example:
../document/id ---
  --- hasComment -- CommentId --- [ authorId -- val, isMajor -- val ],
  --- hasComment -- CommentId --- [ authorId -- val, isMajor -- val ]
....

**Comment by aw3s0me** [comment]
current results Turtle:
@prefix ns1: http://purl.org/dc/terms/ .
@prefix ns2: http://purl.org/dc/dcmitype/ .
@prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .
@prefix xml: http://www.w3.org/XML/1998/namespace .
@prefix xsd: http://www.w3.org/2001/XMLSchema# .
@prefix oa: http://www.w3.org/ns/oa# .

http://fiduswriter.org/document/5 a http://xmlns.com/foaf/0.1/Document .

http://fiduswriter.org/document/5/comments/1263735095 a oa:Annotation ;
    http://eis.iai.uni-bonn.de/Projects/OSCOSS/reviews/isMajor true ;
    oa:annotateAt "2016-..."^^xsd:dateTimeStamp ;
    oa:hasBody "fef" ;
    oa:annotatedBy "alex" ;
    oa:hasTarget  http://fiduswriter.org/document/5 . # lazy solution

# How to represent structured targets? See http://www.openannotation.org/spec/core/20130208/specific.html#TextPositionSelector (not urgent); in our case you can use blank nodes:

# ... oa:hasTarget [ a oa:SpecificResource ; oa:hasSource <....document> ; oa:hasSelector [ a oa:TextPositionSelector; ... ] ] .

http://fiduswriter.org/document/5/comments/1600459977 http://eis.iai.uni-bonn.de/Projects/OSCOSS/reviews/ false ;
    ns2:Text "" ;
    ns1:creator "alex" .
http://fiduswriter.org/document/5/comments/2046924673 ns2:Text "Editor1" ;
    ns1:creator "editor1" .
http://fiduswriter.org/document/5/comments/2281243457 ns2:Text "Reviewer1" ;
    ns1:creator "reviewer1" .
http://fiduswriter.org/document/5/comments/2973318999 ns2:Text "Editor2" ;
    ns1:creator "editor2" .
http://fiduswriter.org/document/5/comments/4057943753 ns2:Text "Reviewer2" ;
    ns1:creator "reviewer2" .
http://fiduswriter.org/document/5/comments/408789226 ns2:Text "Author2" ;
    ns1:creator "alex" .

**Comment by aw3s0me** [comment]
Probably not possible to implement Text Position Selector, because content of document is not a plain text.
I leave this task by this commit: https://github.com/OSCOSS/fiduswriter/commit/50eb0ac8aadd5ba2301b163ad063149cdf00bbe6
Until we choose proper Selector model.

**Comment by clange** [comment]
It may indeed be necessary to look around for other, more complex selectors. They are not specified in _this_ W3C standard, but maybe some other people have specified such selectors on top of this standard. Figuring this out by searching mailing lists and/or studying literature could be a task for @sadeghiafshin and/or @vinaymodi – I can discuss this with you on Friday. (@aw3s0me of course you would also be most welcome to do this, but I suppose there is enough implementation for you to focus on right now. But an extended RDF model of comments could be one building block of a lab topic, for example.)

**Comment by johanneswilm** [comment]
Hey @clange, where can I find out more about requirements related to your RDF plans? I thought RDF in comments was a pet project of @aw3s0me for development purposes. What are you guys hoping to achieve by adding this? So far I see that we have a few MB of added dependencies. That is fine, as long as there is some kind of purpose to it. I cannot find anything about it in Work Package 1.

You can of course program whatever you guys want, but if it's completely without practical purpose, I think it would probably be best to separate it in a fork that we then don't merge.

**Comment by clange** [comment]
@johanneswilm in short there are no explicit requirements, and this RDF export is definitely not something that I imagine to be merged into the master branch of Fidus Writer any time soon.

My reasoning was to do this as an investment into the future: being able to export certain structural information about a document in a way that can be understood universally (i.e. in the self-describing RDF data model), to facilitate the integration of external services into a document.

As of now this is far from productive applicability and should therefore not be merged into the master.

**Comment by johanneswilm** [comment]
@clange Ok, understood! 

Lets' try to remove the RDF parts that have been merged upstream already then. Embedding RDFa into HTML document export is also doable, and required a lot less work and no new dependencies.

**Comment by aw3s0me** [comment]
Close due to irrelevance for this iteration and not supposed to be in current sprint
