### ISSUE TITLE
Sometimes changes are not seen on other computer

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#17]

**Comment by aw3s0me** [comment]
If we type comments or text sometimes changes are not seen. But if we refresh page, it is visible.

**Comment by johanneswilm** [comment]
Are you using your own fork? I think there still may be merging issues with it.

**Comment by johanneswilm** [comment]
This may come in handy to test collaborative editing. It allows you to use the Chrome Selenium driver to test collaborative editing on a Fidus Writer installation.
[test-driver.zip](https://github.com/OSCOSS/fiduswriter/files/170192/test-driver.zip)

**Comment by aw3s0me** [comment]
Actually we tested it on fiduswriter.gesis.org. Probably I have same issues, because of merging.

**Comment by johanneswilm** [comment]
I don't know whether that server is updated. We used a different server for final testing last time.

**Comment by johanneswilm** [comment]
I fixed at least one bug that caused this today in https://github.com/fiduswriter/fiduswriter/commit/d6e80c926d4c2b3403b59b45ef4216e0e50987c3
