### ISSUE TITLE
There should be a comment-only role

### ISSUE THREAD

**Issue by clange** [OSCOSS/fiduswriter#25]
Typically the reviewers and the editor are allowed to comment on an article but not to edit it.

**Comment by vinaymodi** [comment]
Moving this to April Sprint - New features & Enhancements.

**Comment by aw3s0me** [comment]
Now. I hide buttons except commenting buttons for reviewer and editor roles. And check on server side types of sent changes.
Need to do:
1) On the clientside: Notice there is a filter of the transforms. right now it only checks whether there are the same amount of documents as there are supposed to be. That works well for users who have write access.: https://github.com/fiduswriter/fiduswriter/blob/3.0/document/static/js/es6_modules/editor/editor.js#L382-L399 . You will want to adjust that to work for people with other types of access as well.
2) there is a separate function for the footnote editor. It just checks that no footnotes are being merged

**Comment by aw3s0me** [comment]
My ideas how to solve (1) We have OnFilterTransform. This handler we need to allow/disallow editor transformations.
Solution:
just before if (transform.doc.childCount === 6).. i do if (role==comment_only && and (steps.type !== add Mark || steps.type !== remove Mark)) return prohibited = true?

**Comment by aw3s0me** [comment]
As for (2) footnote content doesn't permit comments at all (only the entire footnote can be commented on). So just leave it for timebeing.

**Comment by johanneswilm** [comment]
@aw3s0me:

> As for (2) footnote content doesn't permit comments at all (only the entire footnote can be commented on). So just leave it for timebeing.

The effect of this will be that the editor/commentor will be able to edit the footnotes, but nothing else. You will have to add a single line (or three) in the onFilterTransform for footnotes that simply disallows any type of editing of footnotes if the user role is commentator or reviewer.
