### ISSUE TITLE
Not updating comments correctly

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#29]
How to recreate: 
1. Create document
2. Open 5 tabs.
3. Add some comments
4. User 1, close and reopen document
5. User 1. add new comment.
6. This comment will not appear on other users screens

Why it happens. The problem can be caused by ProseMirror Update Scheduler. Need to check theEditor.mod... and theEditor.pm.mod...
How to see comments: theEditor.doc.comments

**Comment by johanneswilm** [comment]
Hey, the updatescheduler related stuff I fixed in the main branch last week. Please pull latest changes of 3.0 branch. What I did not fix are any potential serverside or other issues related to this.

**Comment by aw3s0me** [comment]
Description of thisnweird bug: It generated ID for session, using maximum number of participants, so when you close session and reopen it, it can give you same id that already can exist in dictionary.
So now: it is temporary solution: I generate it only by using randint. But i think it is better to switch to uuid4?
Problem of randint: Possible to hack, just by seeing github.... and seeing max # of randint

**Comment by johanneswilm** [comment]
@aw3s0me Do you mean this piece:

> self.id = max(self.doc['participants'])+1

? The way that should work, is not that it takes the number of participants and adds one, but rather the maximum ID of any participant and then adds one. See

`> max({2:{},10:{}})+1`
`11`

So I don't there is the possibility of a clash there. Using a random ID instead does introduce the possibility of a clash.

**Comment by johanneswilm** [comment]
If a connection is closed, then the ID of that participant should be eliminated from the pool of used IDs. Every user receives an update with a list of current participants. So why would it matter that an ID is being reused?

The important thing should be that no user ever should have the same ID at the same time.
