### ISSUE TITLE
Submit empty comment box by other user

### ISSUE THREAD

**Issue by mazamat** [OSCOSS/fiduswriter#32]
When user 1 click on comment button, comment box appears immediately on user 2 editor too.
User 2 can write on the comment box which opened by user 1 and pressed "submit" and now it looks like that comment was made by user 1.

**Comment by mazamat** [comment]
When user clicks on comment button to write a comment but quit to write , the box remains even after the page refreshes. If user doesn’t submit a comment or cancel it, it must be automatically remove from the page after refreshing

**Comment by johanneswilm** [comment]
I am workingon this upstream

**Comment by johanneswilm** [comment]
has been fixed upstream
