### ISSUE TITLE
OJS:FW Convey roles between OJS and FW 

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#33]
Roles defined and assigned to users in OJS and Roles assigned to users in FW should match to each other.

**Comment by johanneswilm** [comment]
One factor to keep in mind: User roles in FW are defined per document. So if user A has write, read, comment or editor access document 1, this does not mean that user A also has those same access rights to document 2.

I don't know how user roles are assigned in OJS.

**Comment by afshinsadeghi** [comment]
@johanneswilm : In OJS roles are per user in a journal, that can be possible that one author sends more than one document to a journal, but the important is that: 
1. His role is constant in that journal
2. A user can have multiple roles, for example, an author can be a reader and a reviewer as well.

**Comment by johanneswilm** [comment]
Ok, that sounds as if they should be compatible. In FW roles are per document. So one user cannot simultaneously be an author and a reviewer of the same document. But I assume OJS doesn't allow that either.

**Comment by afshinsadeghi** [comment]
Yes, OJS does not allow that implicitly, as the procedure to submit and the procedure to review items are different, so by that, we can recognize that for what reason a user of OJS is in FW.

**Comment by afshinsadeghi** [comment]
The functionality has usage in the workflow of submitting a paper from FW to OJS.

**Comment by afshinsadeghi** [comment]
We solved the problem by hardwiring roles in FW : we added the apply role related rules by type of requests that the OJS gets from FW. For example, In OJS We assume that only a reviewer can submit a review in FW and etc
