### ISSUE TITLE
OJS:FW User identification

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#34]
A user belonging to OJS should not need to be made again inside FW, but both FW and OJS must remember which user in OJS is active in FW and know their history.

**Comment by johanneswilm** [comment]
@sadeghiafshin What is meant by "know their history" and "is active"?

What could be done is to write a django app that listens to the signals of creating new users and users changing their passwords. And -- given that the OJS API allows for this -- can then create users and update passwords for such users in OJS.

**Comment by afshinsadeghi** [comment]
@johanneswilm: By history It means if a user was active before, his id and roles and created/edited/reviewed documents should be kept in FW.

**Comment by johanneswilm** [comment]
A user's file history is not currently stored in FW. This would have to be added if wanted.

**Comment by johanneswilm** [comment]
@sadeghiafshin Can we close this?

**Comment by afshinsadeghi** [comment]
yes.
