### ISSUE TITLE
OJS:FW document identification

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#35]
Once a document that is sent from OJS to FW,  it must be recognized by FW later again by later access, and its history, including comments etc, must be kept and remembered by FW by later access that originates from OJS.

**Comment by johanneswilm** [comment]
**If sending the document itself (as done in previous integration demo)**

The comments and databases of used images and bibliography are embedded in the document itself. When a document is imported, bibliography items and images are matched with the users existing times. If they are the same as the existing ones, the existing ones are used. Except access rights, everything about the document is contained in the document itself, so there is no need to remember anything about it for Fidus Writer.

**If using the proposed 'centralized model'**

As I understand the centralized model you guys want to work on, you only want to send a link to the FW document to OJS. In this case, comments, etc. should be preserved in FW automatically.

**Comment by afshinsadeghi** [comment]
As we intend to do the review and read, and authoring inside FW, it only makes sense if we hold comments, etc in FW.

**Comment by johanneswilm** [comment]
Yes, comments are stored as a field on the document model itself (see [1]), so you won't have to program anything extra for comments to stay with documents. Only when the document is opened, the comment json is unpacked and the comments inside are shown to the user.

[1] https://github.com/fiduswriter/fiduswriter/blob/3.0/document/models.py#L11-L38

**Comment by afshinsadeghi** [comment]
Then I close this.
