### ISSUE TITLE
Add check for bold/italic/links marks in editor.js transformation

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#37]
For comment-only role on the client side I check only addMark, removeMark, but I also have to check which type of mark is that, because addMark can contain not only comment, but bold, italic, link transformations

**Comment by aw3s0me** [comment]
Implementation comments:

johanneswilm [5:41 PM] 
you need to check for mark.type===comment
you would have to look through the sourcecode of PM.
or... catch the transfofrmation in editor.js
just do a console.log(...) to get it in the javascript console
and then try out what happesn creating a comment vs the other ones

**Comment by johanneswilm** [comment]
@aw3s0me Here, this is what a transform adding a comment looks like

![comment_add_transform](https://cloud.githubusercontent.com/assets/595512/15269330/ba9f1b2e-19fb-11e6-84f6-8b4bfbd3c241.png)

**Comment by johanneswilm** [comment]
So just check for param.type.name === 'comment'

**Comment by aw3s0me** [comment]
jQuery.inArray(step.type, allowedCommentOnly) !== -1 && step.type.name === 'comment'
in editor.js. OnTransform function

**Comment by johanneswilm** [comment]
Yes, almost, something like

allowedCommentOnly.indexOf(step.type) !== -1 && step.param.type.name === 'comment'

in the onFilterTransform function.
