### ISSUE TITLE
User logout and profile dropdown doesn't work after clicking once

### ISSUE THREAD

**Issue by vinaymodi** [OSCOSS/fiduswriter#42]
User logout and profile menu dropdown doesn't work after clicking once.

**How to reproduce:** Click logout menu dropdown that is located on the top right. When dropdown shows, click anywhere on the page to close this dropdown. Now try again the same thing, menu will not open.

**Possible cause:** This issue usually occurs due to not handling DOM events properly. Registering an event multiple times causes multiple tigers of the same event.

**Comment by vinaymodi** [comment]
Fixed click event's on and off. Tested in FF and Chrome.

**Comment by johanneswilm** [comment]
This was fixed upstream about a week ago. Sorry, didn't see this bug report before now.
