### ISSUE TITLE
Documentation generation doesn't work

### ISSUE THREAD

**Issue by vinaymodi** [OSCOSS/fiduswriter#43]
Project documentation that is available in 3.0 branch doesn't generate html files. User can not generate documentation from reStructured Text sources.

**How to reproduce**: Run `make html` from inside _docs_ directory. It generates several errors and doesn't create __build_ directory where documentation in html format should auto generate.

**Possible reasons**: Incorrect dependencies and configuration.

**Closer look**: Found few lines of code that has no relation with the project structure and project source code. Appears to have been copied from third party source as it is. Project is using Django 1.9.x but dependency configured for document generation was Django 1.8. This breaks how Django loads models for sphinx to access them.

**Comment by johanneswilm** [comment]
Talk to Aleksandr about this. He created this recently. Notice instructions for how to create docs in README file.

**Comment by vinaymodi** [comment]
If anybody testing this, pls wait. I will update README file to ensure that you get right version of sphinx. For impatient, please update sphinx to latest 1.4.4 then try.

**Comment by johanneswilm** [comment]
@vinaymodi Please upgrade first to the latest version on the 3.0 branch before you change the REAME.md file. The README.md file has changed. Changign it without pulling the latest will cause more stuff breaking.

**Comment by johanneswilm** [comment]
Also, please see https://github.com/OSCOSS/fiduswriter/issues/44 before proceeding any further with this. @vinaymodi
