### ISSUE TITLE
not up to date, accidental forking

### ISSUE THREAD

**Issue by johanneswilm** [OSCOSS/fiduswriter#44]
Hey, @vinaymodi Could you please undo https://github.com/OSCOSS/fiduswriter/commit/d442ad2ce5fd2c9737ea6a680ee2faa3ddca8eda . As I mention in the comment there, this was fixed upstream a week ago, so the two fixes on top of each other mean that it's now breaking. You should probably pull the latest version directly from the fiduswriter repo.

~~@aw3s0me According to @vinaymodi's comments here, it sounds as if the sphinx code was copied from somewhere else. This is generally not a problem, as long as the license of the original code is so permissive that it allows you to commit this as if it were your own code. May I ask: Where did you find this?~~

**Comment by johanneswilm** [comment]
~~@aw3s0me Looking a bit more at your code, it appears at least some of it may come from this blog entry: https://matijakolaric.com/writing-documentation/~~

~~The author seems to be fine with others reusing this, so that's good. Bu unfortunately the person has not signed any licensing agreement with Fidus Writer so we cannot be entirely sure. If this is where the code comes from, could you send the person an email, asking wehther you can get this code under something like a BSD license?~~

**Comment by aw3s0me** [comment]
@johanneswilm , is the situation clarified? Should I also write a message? Should I close the issue?

**Comment by johanneswilm** [comment]
@aw3s0me The issue of the legal situation of that file has been clarified. If you are not on that mailing list, I'll forward it to you. The other issues are still there, so let leave it open until that has been clarified.
