### ISSUE TITLE
Disappearing comments

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#5]
Json exists in db, but container is empty

![screenshot from 2016-01-21 11 07 27](https://cloud.githubusercontent.com/assets/3517287/12477361/60961af4-c02f-11e5-980b-59941634d826.png)
![screenshot from 2016-01-21 11 06 05](https://cloud.githubusercontent.com/assets/3517287/12477360/60934ac2-c02f-11e5-82da-e074d5211579.png)

**Comment by aw3s0me** [comment]
if u click on black circle with white x, and rerender page
it will not render comment, but will leave the text grey highlighting. Moreover, the comment will exist in json

**Comment by aw3s0me** [comment]
This bug appears only if you open database browser simultaneously with fidus writer in browser (simultaneous access to database makes this error)

**Comment by afshinsadeghi** [comment]
@aw3s0me  would you please put this issue in the priority?

**Comment by aw3s0me** [comment]
@sadeghiafshin Could you please write here, how to recreate this bug in editor? For timebeing, comments work properly in editor.

**Comment by afshinsadeghi** [comment]
@aw3s0me  Then open several browser tabs(at list 5) and see if it works properly while changing in several tabs, and if everything was fine please close this issue.

**Comment by mazamat** [comment]
1-When user click on comment button to write a comment but doesn't write anythinh, the box remains even after the page refreshes. If user doesn’t submit a comment or cancel it, it must be automatically remove from the page after refreshing.


 2-When user 1 click on comments button, it appears immediately on user 2 page.
User 2 can write on the comment box which user 1 open for him/herself .
