### ISSUE TITLE
Complete The CSS for ACM and Springer for editor page

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#56]
please check adding photos

**Comment by clange** [comment]
@sadeghiafshin if this issue is related to #55, #61 and/or #62, please link them appropriately and add some explanatory sentences. I created #61 and #62 as new issues because I couldn't make sense of this issue and its description.

Oh, and please _assign_ _this_ issue to someone.

**Comment by afshinsadeghi** [comment]
@s6fikass  please take this one in Jan 2017

**Comment by afshinsadeghi** [comment]
@clange I can not assign the issues in this repository. Do you know who created this repo branch?

**Comment by clange** [comment]
@sadeghiafshin sorry, didn't see this earlier. #62 is an issue in the same repository, which you successfully reassigned. Does it work now to reassign this one?

**Comment by afshinsadeghi** [comment]
@clange Fakhri was maintaining a copy of the repository. I reassigned the issue it Firas. Thanks. @s6fikass  if it is finished please let me know by mentioning in your note and close it.

**Comment by afshinsadeghi** [comment]
closed as we continue that in #62
