### ISSUE TITLE
OJS integration: on review complete button, if Journal Editor creates a new review round in OJS, ojs tells FW to make a new revision

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#60]
We are adding the second round to review in FW side :
After Journal editor decides to let the article to the second review round.   FW takes a request from OJS integration plugin and must create the second version of the file open to edit or revision for authors.

**Comment by afshinsadeghi** [comment]
name of url : newRevision

**Comment by momenifi** [comment]
The authors edit the reviewed article and consider the comments of reviewers. When revision is done, the author who submitted article for first time, submit it again through 'finish submission' button. The process of submiting the Revision is the same as the first submission, just one difference: If document is a Revision, submission_id and version_id will be sent to ojs too. If Ojs recieves a submission_id, means that it is not a new article, but a new revision.

**Comment by afshinsadeghi** [comment]
FW will need the document_id

**Comment by afshinsadeghi** [comment]
assumption: on every review round, reviewer only sees one finalized revision. of course the author can edit and revise the document as many times he wants but reviewer sees only submitted version

**Comment by afshinsadeghi** [comment]
part one is done and tested:On decide of editor for new revision, plugin calles a url in FW to let it know we have a new revision when FW takes the new revision command, it creates a new file for reviewers

part two is left: On second submit of the author for Second revision in FW, the OJS plugin takes new variables:
submission_id and version_id using these variables "single signing on" changes for reviewer**

**Comment by momenifi** [comment]
In FW you can check if document is submitted or not. If status of document is submitted, by submitting the revision, it send submission_id and version_id to OJS:
https://github.com/momenifi/fiduswriter/blob/FwOjs/document/static/js/es6_modules/submit/journal.js#L71
@sadeghiafshin Please test it.

**Comment by afshinsadeghi** [comment]
tested
