### ISSUE TITLE
citing from sowiport database from inside editor of FW

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#66]
After it will be finished then writer will be able to search in sowiport database and cite directly from its results

**Comment by johanneswilm** [comment]
A general search feature for new bibliographic items would also be of interest to Fidus Writer (to add citation sources from sites such as crossref or worldcat). 

But from my understanding of this branch, it is not so much about making a general search interface and more about experimenting with Solr Index and other technologies and not something to be used in the long-term and merged upstream, correct?

At any rate, if this is to be used in real-world use-cases, it seems to be a good idea only to use the Solr Index to the extent that it is necessary for the experiment: for searching, not for final extraction. 

Converting the data from the raw solr output to the format FW expects it in, is a major science in itself. But Sowiport has an export feature for bibtex, and a complex bib(la)tex converter for FW does exist [1], so the easiest solution may be to take the id as it comes out of the solr raw data [2], then request the bibtex version of that entry [3], and then process that. If the expeirment allows the usage of these bibtex export filters for the final data, that should make it a lot easier to program without having to deal with the many differnet field types that exist.

[1] https://github.com/fiduswriter/biblatex-csl-converter

[2] For example "id":"gesis-solis-00625037"

[3] For example http://sowiport.gesis.org/Record/gesis-solis-00625037/Export?style=BibTeX

**Comment by afshinsadeghi** [comment]
pushed by Johannes.

**Comment by afshinsadeghi** [comment]
it is not using keys.
it can work from two places in the interface.
