### ISSUE TITLE
Bibtex service for FW from SCM-KG

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#74]
(FW requires bib(la)tex export (biblatex manual) or bib db)

**Comment by afshinsadeghi** [comment]
setting up the server.

**Comment by johanneswilm** [comment]
See plugin https://github.com/fiduswriter/fiduswriter-citation-api-import

**Comment by afshinsadeghi** [comment]
better to extend a copy of plugin above

**Comment by afshinsadeghi** [comment]
I had the server setup in http://butterbur10.iai.uni-bonn.de/ 
installed triple repository

**Comment by afshinsadeghi** [comment]
extending https://github.com/fiduswriter/fiduswriter-citation-api-import

**Comment by afshinsadeghi** [comment]
I made a fork of https://github.com/fiduswriter/fiduswriter-citation-api-import 
 and pushed my code here:
https://github.com/OSCOSS/fiduswriter-citation-api-import
. it is not yet finished

**Comment by afshinsadeghi** [comment]
files changed: 
in https://github.com/OSCOSS/fiduswriter-citation-api-import/tree/master/citation-api-import/static/js/es6_modules/citation-api-import

index.js
templates.js

added: scmkg.js

@johanneswilm to debug it should I install the plugin each time I change it? or can I edit the installed version ? do you know where the installed plugin goes?

**Comment by johanneswilm** [comment]
To debug: link the app folder of the plugin directly into the main fiduswriter installation. The pluginfolder is for example "ojs".

**Comment by afshinsadeghi** [comment]
pushed the code
