### ISSUE TITLE
Bug: when number of footnotes are greater in a document than 12 the footnote numbers does not update automatically

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#87]
Bug: when number of footnotes are greater in a document than 12 the footnote numbers does not update automatically

**Comment by johanneswilm** [comment]
@sadeghiafshin Cannot reproduce. Do you mean the numbering does't update? That would be strange, given that the numbering happesn with CSS counters.

**Comment by afshinsadeghi** [comment]
@johanneswilm I tried with adding the 13 in the middle of the text that this happened. I tried to repeat now to take a photo but did not happen.

**Comment by johanneswilm** [comment]
@sadeghiafshin Hmm, odd. I think it's probably a bug with numbering or adding of the footnote in a specific place (such as in a code block or a list of the 4th level or some such thing) that is the problem, and it would be good to find where this error occurs. So if this happens to you again, try to see if you can find anything unusual about the placement.
