### ISSUE TITLE
Filtering server side by role

### ISSUE THREAD

**Issue by aw3s0me** [OSCOSS/fiduswriter#9]
support for adding discussion comments in different roles and with different visibility profiles  
- readers should be able to ask questions to the authors in public or confidentially;  
- authors’ comments should be configurable to be invisible to reviewers;  
- reviewers’ comments should be configurable to be visible to the editorial board only, or to others, etc.),  
- for a filtered and ordered lookup of comments (e.g., all comments by reviewer 1, major concerns first).

**Comment by aw3s0me** [comment]
My questions:
readers should be able to ask questions to the authors in public or confidentially;   It looks like a private message
actually server side filtering in this case gets complicated but doable
moreover their visibility should be stored in json. Visibility is applied to document? or per comment?

**Comment by aw3s0me** [comment]
Configuration example (configuration.py): 
VISIBILITY = { 
    'author': {'author' : ['always'] }, 
    'reviewer': {'author' : ['revision', 'publication'], 
                         'spec_rev': ['always'], 
                         'all_rev' : ['discussion', 'revision', 'publication'],  
                         'editor' : ['always'] }, 
    'editor' : { 'author' : ['revision', 'publication'], 
                         'spec_rev': ['always'], 
                         'all_rev' : ['always'],  
                         'editor' : ['always'] } 
}

**Comment by clange** [comment]
Great; this configuration example looks appropriate and sufficiently flexible for future adaptations.

**Comment by aw3s0me** [comment]
Leave it, until we fetch roles from OJS. This commit is the latest: https://github.com/OSCOSS/fiduswriter/commit/f9869b12bdce30d3790deea55936fe1bfebd2796

**Comment by aw3s0me** [comment]
about real time problem
i think we dont have to implement it
because the document will be in workflow
and during this workflow, some users will not have an access to document at all
Implementation idea:
Outgoing requests: just filter comments in send_updates function ws_views
Incoming requests: check whether user has needed access_rights

**Comment by johanneswilm** [comment]
If you don't implement this and just rely on documents not being accessible, you don't really need to implement user access roles at all. Having a half-finished implementation is not a good idea.

**Comment by johanneswilm** [comment]
@aw3s0me Could you let me know if you are not going to do this? 

I have been holding of fixing the "can read' editing mode because I knew you were working on this part of the code over the past few weeks. If you end up not doing this, or only doing it half-way, then it's probably better that you guys fork your code and that I fix it in the main repository so that the two basic modes: "can write+read" and "can read" and possibly a third mode "can comment" work. This should be doable with just a few lines of code, as I explained to you in the chat earlier, whereas you currently seem to be programming something much more complex which I don't quite understand the meaning of.

**Comment by johanneswilm** [comment]
Note: "read only" and "comment only" simple modes have been implemented and merged in 3.0 branch.

**Comment by johanneswilm** [comment]
> about real time problem
> i think we dont have to implement it
> because the document will be in workflow
> and during this workflow, some users will not have an access to document at all

@aw3s0me At the last meeting it became clear that the centralized access module means that authors can access documents and reviewers can simultaneously comment on them without those comments being visible to the author. So this means that realtime filtering of comments is needed.

**Comment by afshinsadeghi** [comment]
task is covered by other issues. we have it now.
