### ISSUE TITLE
Should this still be a fork of fiduswriter/fiduswriter?

### ISSUE THREAD

**Issue by clange** [OSCOSS/fiduswriter#90]
Looking at the root of https://github.com/OSCOSS/fiduswriter this repository now looks like a collection of material _related_ to Fidus Writer, but it no longer contains a fork of the sources of Fidus Writer. If that's correct, then maybe we should no longer say that it is a fork.

**Comment by johanneswilm** [comment]
@clange That is correct. it is not a fork, and it really never has been. Whenever the fork was too large, it ended up creating problems.

Do you mean the link under the title? Unfortunately Github no longer allows removing such links. There really should be nothing in this repository at all -- we would close it down if we could, but then we would lose the issue list.

**Comment by clange** [comment]
Oh, I see, yes, the link below the title confused me. Indeed, the top-level README already reflects the current state.

**Comment by johanneswilm** [comment]
@sadeghiafshin Can we delete the videos in thsi repository? We have posted them to youtube, and I believe we have remvoed all the links that came here earlier.

**Comment by johanneswilm** [comment]
@clange A few years ago one could remove that link by request by sending an email to the Github staff. But it seems this option is gone now.

**Comment by afshinsadeghi** [comment]
@johanneswilm I removed them.
