### ISSUE TITLE
extend export html function of FW to include titles and comments

### ISSUE THREAD

**Issue by afshinsadeghi** [OSCOSS/fiduswriter#92]
extend export html function of FW to include titles and comments

**Comment by afshinsadeghi** [comment]
The Progess till now: Adding export item for dokieli to the export menu and creating a sample file.

@csarven  here is a sample of created file by export function. by changing the format to ACM and Springer format the font changes, but for ACM it does not become two column. 


[document.html.zip](https://github.com/OSCOSS/fiduswriter/files/1205729/document.html.zip)

**Comment by csarven** [comment]
IIRC, for ACM stylesheet to work, the content (excluding things like h1, authors..) has to be wrapped with `<div id="content">`. I don't particularly like this but having the HTML work with different CSS, we needed that wrapper. Would like to find a way to do it without that wrapper but the CSS is tricky. See the HTML example here: https://dokie.li/acm-sigproc-sp

**Comment by afshinsadeghi** [comment]
done
