### ISSUE TITLE
WP4 Scenario 2 "data-based citations"

### ISSUE THREAD

**Issue by clange** [OSCOSS/fiduswriter#95]
when citing a data-based table from some other Fidus Writer article (i.e. a table with an explicit link to a dataset), do not just cite the table, but also the dataset (e.g. via its BibTeX/DOI).

**Comment by clange** [comment]
![Drawing: fidus writer dataset citation](https://user-images.githubusercontent.com/649182/28162740-6fce905e-67c8-11e7-9d14-226e4be680cf.jpg)

**Comment by afshinsadeghi** [comment]
We currently want to import  the metadata of the dataset. like doi, URI, etc
for example:
https://dbk.gesis.org/dbksearch/sdesc2.asp?no=5989

**Comment by afshinsadeghi** [comment]
that is to make it easier for the refering to an article to directly get to the dataset.

**Comment by afshinsadeghi** [comment]
for these datasets in this website we can intake the meta data (which is URI) of a dataset http://270a.info/

**Comment by s6fikass** [comment]
@clange  
we could do this in two ways:

1. We add a new way of citation called DOI ( where we add properties such as link to data and title and DOI) this can be done with the current.
2. Add a special link such for that. eg. [ DOI 10.3233](http://www.semantic-web-journal.net/issues)

**Comment by johanneswilm** [comment]
Hey, please don't add new citation types. The citation types and attributes all follow standards and we save years of implementation work by continuining to follow these standards.

**Comment by johanneswilm** [comment]
Probably the best is to add a note to the citation. Saying something about the original source. This should show in some citation styles. It's already there, so nothing needs to be done other than test whether it works and which citation style shows notes. Worst case: hack an existing citation style to add the note in the output.

**Comment by johanneswilm** [comment]
Adding a note will also be more compatible with most uses. Most things in the social sciences don't have DOIs. Datasets are quute an exception as data sources in social sciences.

**Comment by clange** [comment]
Re. "datasets are quite an exception" – well, sure, but we want to provide better support for working with datasets so that they become less of an exception in future.

**Comment by johanneswilm** [comment]
Right. But then it's probably not the best idea to treat it differently than all other citation types cause that will just mean noone gets the feature and we produce output incompatible with everything.
But what we can do is check that it works and if it doesn't, add it in a way that is compatible with all the existing citation types. Possibly also adding some documentation on how to achieve the dual-citation result would be helpful.

**Comment by afshinsadeghi** [comment]
so in practice, we add more fields like doi etc to the citation fields we currently use. and make them searchable by them.Adding documentation for this new feature is also important.

**Comment by johanneswilm** [comment]
This fields are now handled in the library we have together with some Zotero people. We follow biblatex and CSL. DOI is already one of the fields so nothing more needs to be done.

**Comment by afshinsadeghi** [comment]
then I close this.
